name: Install Dependencies
description: "Setup node, bun dependencies"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.15
    # - name: Setup Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20
    - name: Install project dependencies
      run: bun install
      shell: bash
